name: CI

on: [ push ]

jobs:
  test-sqlcipher-bundled:
    name: Test ${{ matrix.os }} (bundled SQLcipher + NSS)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: stable${{ matrix.host }}
          targets: ${{ matrix.target }}
      - uses: Swatinem/rust-cache@v1
        with: { sharedKey: fullBuild }

      - run: apt-get install nss
      - run: cargo test --features 'modern-full bundled-sqlcipher-nss' --verbose
