name: CI

on: [ push ]

jobs:
  test-sqlcipher-bundled:
    name: Test ${{ matrix.os }} (bundled SQLcipher + NSS)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: stable${{ matrix.host }}
          targets: ${{ matrix.target }}
      - uses: Swatinem/rust-cache@v1
        with: { sharedKey: fullBuild }

      - run: sudo apt-get -V install libnss3 --reinstall
      - run: ls /usr/
      - run: ls /usr/include/
      - run: ls /usr/local/include/
      - name: test NSS
        env:
          NSS_DIR: /usr/include/nss
        run: cargo test --features 'modern-full bundled-sqlcipher-nss'
