name: CI

on: [push]

jobs:
  test-sqlcipher-bundled:
    name: Test ${{ matrix.os }} (bundled SQLcipher + NSS)
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        # TODO: find a way to test this on windows :(

    steps:
      - uses: actions/checkout@v2
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: stable${{ matrix.host }}
          targets: ${{ matrix.target }}
      - uses: Swatinem/rust-cache@v1
        with: { sharedKey: fullBuild }

      - run: cargo test --features 'modern-full bundled-sqlcipher-nss' --all-targets --workspace --verbose

      - name: Add llvm path on Windows
        if: matrix.os == 'windows-latest'
        run: echo "C:\msys64\mingw64\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - run: cargo test --features 'bundled-full session buildtime_bindgen' --all-targets --workspace --verbose
      - run: cargo test --features 'bundled-full session buildtime_bindgen' --doc --workspace --verbose
